language: node_js
node_js:
  - "10.14.1"
cache: npm

sudo: required

notifications:
  email: false

script:
  - echo 'npm ci:' && echo -en 'travis_fold:start:script.1\\r'
  - npm ci
  - echo -en 'travis_fold:end:script.1\\r'

  # start ganache in background
  - npm run ganache &

  # compile our contract
  - npm run compile
